//application.js
export const SET_USERNAME = 'SET_USERNAME'
export const SET_LOGIN_USERNAME = 'SET_LOGIN_USERNAME'
export const SET_TWITCH_ID = 'SET_TWITCH_ID'
export const SET_PROFILE_IMAGE = 'SET_PROFILE_IMAGE'
export const SET_MOD_LIST = 'SET_MOD_LIST'
export const SET_CHANNEL_ACCESS = 'SET_CHANNEL_ACCESS'
export const ADD_CHANNEL_HISTORY = 'ADD_CHANNEL_HISTORY'
export const SET_ROOM_USERS = 'SET_ROOM_USERS'
export const SET_CURRENT_CHANNEL = 'SET_CURRENT_CHANNEL'
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
//modChat.js
export const NEW_MOD_MSG = 'NEW_MOD_MSG'
export const CLEAR_MOD_MSGS = 'CLEAR_MOD_MSGS'

export const TOGGLE_MOD_CHAT_VIEW = 'TOGGLE_MOD_CHAT_VIEW'
//twitchChat.js
export const ADD_TWITCH_MESSAGE = 'ADD_TWITCH_MESSAGE'
export const CLEAR_TWITCH_MESSAGES = 'CLEAR_TWITCH_MESSAGES'

export const ADD_CHANNEL_EMOTES = 'ADD_CHANNEL_EMOTES'
export const ADD_CHANNEL_EMOTE_CODES = 'ADD_CHANNEL_EMOTE_CODES'
export const ADD_CHANNEL_EMOTE_ID_BY_NAME = 'ADD_CHANNEL_EMOTE_ID_BY_NAME'

export const INCREASE_CHAT_MODULE_COUNT = 'INCREASE_CHAT_MODULE_COUNT'
export const DECREASE_CHAT_MODULE_COUNT = 'DECREASE_CHAT_MODULE_COUNT'
export const ADD_TWITCH_CHAT_MODULE = 'ADD_TWITCH_CHAT_MODULE'
export const TOGGLE_SETTINGS_VIEW = 'TOGGLE_SETTINGS_VIEW'
export const REMOVE_CHAT_MODULE = 'REMOVE_CHAT_MODULE'
export const TOGGLE_EDIT_NAME = 'TOGGLE_EDIT_NAME'
export const SET_MODULE_NAME = 'SET_MODULE_NAME'
export const PAUSE_CHAT_MODULE = 'PAUSE_CHAT_MODULE'

export const UPDATE_FILTER_COMMANDS = 'UPDATE_FILTER_COMMANDS'
export const UPDATE_FILTER_SUBSCRIBER_MESSAGES = 'UPDATE_FILTER_SUBSCRIBER_MESSAGES'
export const UPDATE_FILTER_NONSUBSCRIBER_MESSAGES = 'UPDATE_FILTER_NONSUBSCRIBER_MESSAGES'
export const UPDATE_FILTER_DIRECT_MENTIONS = 'UPDATE_FILTER_DIRECT_MENTIONS'
export const UPDATE_FILTER_EMOTES = 'UPDATE_FILTER_EMOTES'
export const UPDATE_FILTER_MOD_MSGS = 'UPDATE_FILTER_MOD_MSGS'